Shrug off failures with newsboat feed refresh unit
Newsboat cannot be made to refresh the feeds while an interactive
instance is already running:

    Error: an instance of Newsboat is already running (PID: 1045489)

Therefore, simply ignore the errors that may occur.  It should be
noted that if the service were to systematically fail, for, say, some
configuration error, then this would forever swallow errors.  A more
appropriate solution should likely be considered.

As to how this "-" here effects the described change, refer to the
COMMAND LINES section of man 5 systemd.service:

    If the executable path is prefixed with "-", an exit code of the
    command normally considered a failure (i.e. non-zero exit status or
    abnormal exit due to signal) is recorded, but has no further effect
    and is considered equivalent to success